name: Test, Upload artifact

on: workflow_dispatch

jobs:
  release:
    name: Build, package and
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Build and package project
        run: |
          rev=$(git rev-parse --short HEAD)
          echo "rev  ${rev}"
          ls
          mvn clean package -DskipTests
          sudo docker build --build-arg GIT_COMMIT=${rev} -t cachewebsite/t:latest -f Dockerfile .
          sudo docker image tag cachewebsite/t nexus.ppustage.dev/cachewebsite-service:${rev}
          sudo docker login -u ${{secrets.NEXUS_USER_NAME}} -p ${{secrets.NEXUS_PASSWORD}} nexus.ppustage.dev
          sudo docker push nexus.ppustage.dev/cachewebsite-service:${rev}